CREATE DATABASE IF NOT EXISTS blinkit_analysis;
USE blinkit_analysis;

CREATE TABLE blinkit_dataset(
Item_Fat_Content VARCHAR(50) ,
Item_Identifier VARCHAR(50) ,
Item_Type VARCHAR(100) ,
Outlet_Establishment_Year INT,
Outlet_Identifier VARCHAR(50) ,
Outlet_Location_Type VARCHAR(50) ,
Outlet_Size VARCHAR(50) ,
Outlet_Type VARCHAR(100) ,
Item_Visibility DOUBLE ,
Item_Weight DOUBLE ,
Total_Sales INT,
Rating DOUBLE
);

select * from blinkit_dataset;

#1.Count the number of unique Item_Type values and list them.
-- Objective - How many item available for sell
SELECT count(distinct Item_Type) AS uniq_item 
FROM blinkit_dataset;


#2. What is the total sales revenue generated by Blinkit from 2011 to 2022?
-- Objective = This helps in measuring company growth potential and setting future targets.
select sum(Total_Sales) as Total_Sales 
from blinkit_dataset;


#3.Find the items with the highest total sales in each year of outlet establishment
-- Objective = Help to identify which item has max in each year
WITH RANK_ AS (
SELECT Item_Type , Outlet_Establishment_Year ,sum(Total_Sales) as total_sale,
DENSE_RANK() OVER (PARTITION BY Outlet_Establishment_Year ORDER BY sum(Total_Sales) desc) AS rnk
FROM blinkit_dataset
group by Item_Type , Outlet_Establishment_Year 
)
SELECT Item_Type , Outlet_Establishment_Year , total_sale
FROM RANK_
WHERE rnk = 1;
-- fruits and vegatable has max sale mostly in every year


#4.Show the average rating for each Item_Type .
-- Objective = Help to identify is customer satisfy with the item or not 
SELECT Item_Type , round(AVG(Rating),1) AS avg_rating
FROM blinkit_dataset
GROUP BY Item_Type
ORDER BY avg_rating DESC;
-- Average rating is between 3.9 and 4.0 in every products, indicating that customers are generally satisfied with the products.


#5.find Outlet_Identifier by Outlet_Size ,Outlet_Type,Outlet_Location_Type.
-- Objective = Help to identify the number of outlets blinkit have and in which location_type
SELECT COUNT(DISTINCT Outlet_Identifier) AS total_outlet_open
FROM blinkit_dataset;
-- total 10 outletts
SELECT 
    Outlet_Identifier,
    Outlet_Location_Type,
    COUNT(DISTINCT Outlet_Size) AS size_count,
    GROUP_CONCAT(DISTINCT Outlet_Size ORDER BY Outlet_Size) AS sizes
FROM blinkit_dataset
GROUP BY Outlet_Identifier ,Outlet_Location_Type;


#6. Find the average sales per Outlet_Type and rank them.
-- Objective = Helps to identify which outlet types generate the highest average sales
SELECT Outlet_Type , AVG(Total_Sales) AS avg_sale,
DENSE_RANK() OVER(ORDER BY AVG(Total_Sales) DESC) AS rnk
FROM blinkit_dataset
GROUP BY  Outlet_Type;
-- Supermarket Type2 has rank 1 than Supermarket Type1  


#7. Show the total sales by Outlet_Size and compare.
-- Objective = Help to identify which outlet size generate maximum sale
SELECT Outlet_Size , SUM(Total_Sales) AS Total_Sales,
DENSE_RANK() OVER(order by SUM(Total_Sales) desc) as rnk
FROM blinkit_dataset
GROUP BY Outlet_Size;
-- medium size outlet has maximum sale , high has low sale


#8. Calculate the average sales per Item_Fat_Content.
-- Objective = Helps identify which fat content type generates the highest average sales, 
-- enabling Blinkit to focus on stocking and promoting the most profitable product categories.
SELECT Item_Fat_Content , AVG(Total_Sales) AS avg_Sales
FROM blinkit_dataset
GROUP BY Item_Fat_Content;
-- mostly has same avg sale 


#9. Find the average sales per Tier (Outlet_Location_Type).
-- Objective = Help to identify which location_type generate avg sale
SELECT Outlet_Location_Type , avg(Total_Sales) AS avg_Sales
FROM blinkit_dataset
GROUP BY Outlet_Location_Type;
-- almost same


#10. Find the average sales per year.
-- Objective = Help in identifying to see whether older or newer outlets perform better over time.
SELECT Outlet_Establishment_Year , AVG(Total_Sales) AS avg_Sales
FROM blinkit_dataset
GROUP BY  Outlet_Establishment_Year
ORDER BY  avg_sales DESC;
-- In 2022, which is the latest year in the dataset, average sales are slightly lower compared to earlier peak years like 2017


#11. Find the yearly sales trends.
-- Objective = Help in identify which years contributed most to overall revenue and spot growth or decline trends.
SELECT Outlet_Establishment_Year , sum(Total_Sales) AS total_sale
FROM blinkit_dataset
GROUP BY Outlet_Establishment_Year
ORDER BY total_sale DESC;
-- 2020 ,2022 is the latest years, but sales have declined compared to previous years


#12. Identify the worst-performing Item_Types (lowest sales) in Tier 3 outlets.
-- Objective = Help to identify which item we need to focus on 
WITH item_rank AS (SELECT Item_Type,Outlet_Location_Type,
DENSE_RANK() OVER(PARTITION BY Outlet_Location_Type ORDER BY SUM(Total_Sales)) AS rnk
FROM blinkit_dataset
GROUP BY Item_Type,Outlet_Location_Type)
SELECT Item_Type,Outlet_Location_Type
FROM item_rank
WHERE Outlet_Location_Type = 'Tier 3' AND rnk <=3;
-- Seafood , breakfast , others have low sale in tier 3


# max sale
WITH item_rank AS (SELECT Item_Type,Outlet_Location_Type,
DENSE_RANK() OVER(PARTITION BY Outlet_Location_Type ORDER BY SUM(Total_Sales) DESC) AS rnk
FROM blinkit_dataset
GROUP BY Item_Type,Outlet_Location_Type)
SELECT Item_Type,Outlet_Location_Type
FROM item_rank
WHERE Outlet_Location_Type = 'Tier 3' AND rnk <=3;
-- fruits and veg , snack foods , household have high sale in tier 3


#13. Show the correlation between Item_Weight and Total_Sale.
-- Objective = Help to identify is sale increase or decrease if size increase or decrease
SELECT 
    (SUM((Item_Weight - avg_w) * (Total_Sales - avg_s)) /
     (SQRT(SUM(POW(Item_Weight - avg_w, 2))) * 
      SQRT(SUM(POW(Total_Sales - avg_s, 2))))) AS correlation
FROM (
    SELECT 
        Item_Weight, 
        Total_Sales,
        (SELECT AVG(Item_Weight) FROM blinkit_dataset) AS avg_w,
        (SELECT AVG(Total_Sales) FROM blinkit_dataset) AS avg_s
    FROM blinkit_dataset
) AS sub;
-- no realtion 


#14. Find which product category has the most consistent sales.
-- Objective = Help to identify which item has stable demand
SELECT `year`,
       Item_Type,
       sales_stddev
FROM (
    SELECT Outlet_Establishment_Year AS `year`,
           Item_Type,
           STDDEV(Total_Sales) AS sales_stddev,
           RANK() OVER (PARTITION BY Outlet_Establishment_Year ORDER BY STDDEV(Total_Sales) asc) AS rnk
    FROM blinkit_dataset
    GROUP BY Outlet_Establishment_Year, Item_Type
) t
WHERE rnk = 1
ORDER BY `year`;
-- Across the years, Seafood ,Breakfast consistently shows the lowest variation in sales, indicating stable demand


#15. Find items that perform well in Tier 1 but poorly in Tier 3 outlets
-- Objective = Helps identify items that achieve significantly higher average sales in Tier 1 outlets compared to Tier 3 outlets, 
-- enabling targeted stocking and promotional strategies.
WITH tier_sales AS (
    SELECT Item_Type,
           Outlet_Location_Type,
           AVG(Total_Sales) AS avg_sales
    FROM blinkit_dataset
    GROUP BY Item_Type, Outlet_Location_Type
),
tier_compare AS (
    SELECT t1.Item_Type,
           t1.avg_sales AS tier1_sales,
           t3.avg_sales AS tier3_sales
    FROM tier_sales t1
    JOIN tier_sales t3 
          ON t1.Item_Type = t3.Item_Type
    WHERE t1.Outlet_Location_Type = 'Tier 1'
      AND t3.Outlet_Location_Type = 'Tier 3'
)
SELECT Item_Type, tier1_sales, tier3_sales
FROM tier_compare
WHERE tier1_sales > tier3_sales
ORDER BY (tier1_sales - tier3_sales) DESC;

# chech why 2020 and 2022 sale decreases
SELECT Outlet_Establishment_Year , sum(Total_Sales) AS total_sale
FROM blinkit_dataset
GROUP BY Outlet_Establishment_Year
ORDER BY total_sale DESC;


SELECT Outlet_Establishment_Year, 
       Item_Type, SUM(Total_Sales) AS total_sales,
       round(avg(Item_Visibility),3) AS avg_visibility,
       round(AVG(Rating),1) AS avg_rating
FROM blinkit_dataset
GROUP BY Outlet_Establishment_Year, Item_Type
ORDER BY Outlet_Establishment_Year, total_sales DESC;

-- Reason 
-- Visibility Changes - Earlier years had higher avg_visibility (~0.09–0.12) for many products.
-- but especially in 2020–2022, visibility dropped for top-selling categories (~0.06–0.07).

-- Ratings remained stable (3.8–4.2) across all years — meaning quality perception was not a major driver of decline.

-- Possible COVID-19 Impact (2020 Onwards)
-- The drop in 2020 aligns with the COVID-19 pandemic period when: Supply chain disruptions limited stock availability.
-- In-store promotions and product visibility decreased due to lockdowns and reduced foot traffic.

-- Recovery in 2022 was partial, as volumes for many high-value categories still didn’t return to 2018 levels

